AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  vy-accruals-sam

Globals:
  Function:
    Timeout: 3

Resources:
  # Lambda для работы с MySQL
  MySQLHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./dist
      Handler: handler.handler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Environment:
        Variables:
          DB_HOST: 'vy-db.c1ccaa4ya7jw.eu-central-1.rds.amazonaws.com'
          DB_USER: 'admin'
          DB_PASSWORD: 'YourPasswordHere'
          DB_NAME: 'vy-accruals'
      MemorySize: 128
      Timeout: 30
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSXrayWriteOnlyAccess
      VpcConfig:
        SubnetIds:
          - subnet-0c2a120f223510812 # Укажите ваш subnet ID
        SecurityGroupIds:
          - sg-0a19000c488ae4093 # Укажите ваш Security Group ID
      Events:
        HttpApi:
          Type: Api
          Properties:
            Path: /{proxy+}  # Это позволит Lambda обрабатывать все пути
            Method: post

Outputs:
  MySQLApi:
    Description: "API Gateway endpoint URL for MySQL Lambda"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"

  MySQLFunction:
    Description: "MySQL Lambda Function ARN"
    Value: !GetAtt MySQLHandlerFunction.Arn
